### ISSUE TITLE
查询offset问题

### ISSUE THREAD

**Issue by lihaolixuewei112612** [yucy/flume-ng-sql-source-json#2]
哈喽，在HibernaterHelper.java这个类的184-193这块offset的代码是有问题吧？
if (!rowsList.isEmpty()){
			if (sqlSourceHelper.isCustomQuerySet()){	sqlSourceHelper.setCurrentIndex(rowsList.get(rowsList.size()-1).get(sqlSourceHelper.getOrderBy()).toString());
}
else{			sqlSourceHelper.setCurrentIndex(Integer.toString((Integer.parseInt(sqlSourceHelper.getCurrentIndex())+ rowsList.size())));
}
 }
因为这边一次查询10000条，而if (sqlSourceHelper.isCustomQuerySet())
这里不为空，那么这里将会一直在查询10000-20000这个范围的数据

**Comment by yucy** [comment]
确实是需要处理一下
